import type { RegistryItem } from './index';

const h = (name: string, slug: string, fileName: string, description: string): RegistryItem => ({
  name,
  slug,
  type: 'hook',
  category: 'utility',
  since: '1.0.0',
  description,
  targetPath: 'src/hooks',
  fileName,
  dependencies: [],
  registryDependencies: [],
  tags: ['hook'],
});

export const hooks: RegistryItem[] = [
  h(
    'useBatteryStatus',
    'use-battery-status',
    'useBatteryStatus.ts',
    'Tracks the device battery level, charging state, and charging/discharging time.',
  ),
  h(
    'useConfirmExit',
    'use-confirm-exit',
    'useConfirmExit.ts',
    'Prompts the user with a confirmation dialog when they try to close or reload the tab.',
  ),
  h(
    'useCopyToClipboard',
    'use-copy-to-clipboard',
    'useCopyToClipboard.ts',
    'Copies a string to the clipboard and exposes a copied state flag.',
  ),
  h(
    'useCountdown',
    'use-countdown',
    'useCountdown.ts',
    'Countdown timer hook — returns remaining seconds and controls.',
  ),
  h(
    'useDebounce',
    'use-debounce',
    'useDebounce.ts',
    'Debounces a value by delaying updates until after the wait period.',
  ),
  h(
    'useDeviceOS',
    'use-device-os',
    'useDeviceOS.ts',
    "Detects the user's operating system from the user agent string.",
  ),
  h(
    'useElementPosition',
    'use-element-position',
    'useElementPosition.ts',
    'Tracks the bounding rect position of a DOM element relative to the viewport.',
  ),
  h(
    'useHover',
    'use-hover',
    'useHover.ts',
    'Returns a ref and a boolean indicating whether the element is hovered.',
  ),
  h(
    'useIdle',
    'use-idle',
    'useIdle.ts',
    'Detects user inactivity after a configurable idle timeout.',
  ),
  h(
    'useIndexedDB',
    'use-indexed-db',
    'useIndexedDB.ts',
    'CRUD operations on an IndexedDB object store with async state management.',
  ),
  h(
    'useIntervalWhen',
    'use-interval-when',
    'useIntervalWhen.ts',
    'Runs a callback on an interval only when a condition is true.',
  ),
  h(
    'useIsMount',
    'use-is-mount',
    'useIsMount.ts',
    'Returns true only on the initial render — useful for skipping effects on mount.',
  ),
  h(
    'useKeyPress',
    'use-key-press',
    'useKeyPress.ts',
    'Returns true while a specific keyboard key is held down.',
  ),
  h(
    'useList',
    'use-list',
    'useList.ts',
    'State hook for an array with push, remove, update, and clear helpers.',
  ),
  h(
    'useLocalStorage',
    'use-local-storage',
    'useLocalStorage.ts',
    'Synced state backed by localStorage with JSON serialisation.',
  ),
  h(
    'useLockBodyScroll',
    'use-lock-body-scroll',
    'useLockBodyScroll.ts',
    'Locks body scroll when active — typically used by modals and drawers.',
  ),
  h(
    'useMap',
    'use-map',
    'useMap.ts',
    'State hook for a Map with set, delete, clear, and has helpers.',
  ),
  h(
    'useMeasure',
    'use-measure',
    'useMeasure.ts',
    'Measures the width and height of a DOM element using ResizeObserver.',
  ),
  h(
    'useMediaQuery',
    'use-media-query',
    'useMediaQuery.ts',
    'Returns true when a CSS media query matches the current viewport.',
  ),
  h(
    'useMouseTrack',
    'use-mouse-track',
    'useMouseTrack.ts',
    'Tracks mouse position (x, y) relative to the window or a specific element.',
  ),
  h(
    'useNetworkStatus',
    'use-network-status',
    'useNetworkStatus.ts',
    'Tracks online/offline status and network connection information.',
  ),
  h(
    'useOnClickOutside',
    'use-on-click-outside',
    'useOnClickOutside.ts',
    'Fires a callback when a click is detected outside the referenced element.',
  ),
  h(
    'usePageLeave',
    'use-page-leave',
    'usePageLeave.ts',
    "Fires a callback when the user's cursor leaves the browser viewport.",
  ),
  {
    ...h(
      'usePermission',
      'use-permission',
      'usePermission.ts',
      'Queries the Permissions API for a given permission name and returns its state.',
    ),
  },
  {
    ...h(
      'usePreviousState',
      'use-previous-state',
      'usePreviousState.ts',
      'Returns the previous value of a state variable or prop.',
    ),
  },
  h(
    'useQueue',
    'use-queue',
    'useQueue.ts',
    'FIFO queue state with enqueue, dequeue, and peek helpers.',
  ),
  h(
    'useRenderCount',
    'use-render-count',
    'useRenderCount.ts',
    'Returns the number of times the component has rendered — useful for debugging.',
  ),
  {
    ...h(
      'useScrollPosition',
      'use-scroll-position',
      'useScrollPosition.ts',
      'Tracks the scroll position of the window or a specific element.',
    ),
  },
  h(
    'useSet',
    'use-set',
    'useSet.ts',
    'State hook for a Set with add, delete, has, and clear helpers.',
  ),
  h(
    'useThrottle',
    'use-throttle',
    'useThrottle.ts',
    'Throttles a value so updates fire at most once per delay period.',
  ),
  h(
    'useTimeout',
    'use-timeout',
    'useTimeout.ts',
    'Runs a callback after a delay with cancel and reset controls.',
  ),
  h(
    'useVisibilityChange',
    'use-visibility-change',
    'useVisibilityChange.ts',
    'Tracks document visibility — fires a callback when the tab becomes visible or hidden.',
  ),
  h(
    'useWindowSize',
    'use-window-size',
    'useWindowSize.ts',
    'Tracks window width and height, updating on resize with debouncing.',
  ),
];
