// Generated by scripts/registry-sources.ts. Do not edit.
export const sourceManifest = {
  "accordion": {
    "files": [
      "components/Accordion/Accordion.tsx",
      "components/Accordion/AccordionBody.tsx",
      "components/Accordion/AccordionHeader.tsx",
      "components/Accordion/AccordionItem.tsx",
      "components/Accordion/index.ts",
      "components/Accordion/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "affix": {
    "files": [
      "components/Affix/Affix.tsx",
      "components/Affix/hooks.ts",
      "components/Affix/index.ts",
      "components/Affix/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "alert": {
    "files": [
      "components/Alert/Alert.tsx",
      "components/Alert/AlertContent.tsx",
      "components/Alert/AlertDescription.tsx",
      "components/Alert/AlertDismiss.tsx",
      "components/Alert/AlertIcon.tsx",
      "components/Alert/AlertTitle.tsx",
      "components/Alert/index.ts",
      "components/Alert/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "animation": {
    "files": [
      "components/Animation/AnimateInView.tsx",
      "components/Animation/Animation.tsx",
      "components/Animation/BounceAnimation.tsx",
      "components/Animation/FadeAnimation.tsx",
      "components/Animation/FlipAnimation.tsx",
      "components/Animation/HingeAnimation.tsx",
      "components/Animation/JackInTheBoxAnimation.tsx",
      "components/Animation/RollAnimation.tsx",
      "components/Animation/RotateAnimation.tsx",
      "components/Animation/SlideAnimation.tsx",
      "components/Animation/ZoomAnimation.tsx",
      "components/Animation/index.ts",
      "components/Animation/types.ts",
      "components/Animation/utils.ts",
      "hooks/useInView.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-in-view"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "aspectratio": {
    "files": [
      "components/AspectRatio/AspectRatio.tsx",
      "components/AspectRatio/index.ts",
      "components/AspectRatio/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "avatar": {
    "files": [
      "components/Avatar/Avatar.tsx",
      "components/Avatar/AvatarFallback.tsx",
      "components/Avatar/AvatarImage.tsx",
      "components/Avatar/AvatarInitials.tsx",
      "components/Avatar/AvatarStatus.tsx",
      "components/Avatar/hooks.ts",
      "components/Avatar/index.ts",
      "components/Avatar/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "avatar-group": {
    "files": [
      "components/Avatar/Avatar.tsx",
      "components/Avatar/AvatarFallback.tsx",
      "components/Avatar/AvatarImage.tsx",
      "components/Avatar/AvatarInitials.tsx",
      "components/Avatar/AvatarStatus.tsx",
      "components/Avatar/hooks.ts",
      "components/Avatar/index.ts",
      "components/Avatar/types.ts",
      "components/AvatarGroup/AvatarGroup.tsx",
      "components/AvatarGroup/AvatarItem.tsx",
      "components/AvatarGroup/AvtarGroupOverflowButton.tsx",
      "components/AvatarGroup/hooks.ts",
      "components/AvatarGroup/index.ts",
      "components/AvatarGroup/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "avatar"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "badge": {
    "files": [
      "components/Badge/Badge.tsx",
      "components/Badge/index.ts",
      "components/Badge/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "breadcrumb": {
    "files": [
      "components/Breadcrumb/BreadCrumbItem.tsx",
      "components/Breadcrumb/BreadCrumbLink.tsx",
      "components/Breadcrumb/BreadCrumbList.tsx",
      "components/Breadcrumb/BreadCrumbPage.tsx",
      "components/Breadcrumb/BreadCrumbSeparator.tsx",
      "components/Breadcrumb/Breadcrumb.tsx",
      "components/Breadcrumb/BreadcrumbEllipsis.tsx",
      "components/Breadcrumb/index.ts",
      "components/Breadcrumb/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "button": {
    "files": [
      "components/Button/Button.tsx",
      "components/Button/ButtonBadge.tsx",
      "components/Button/ButtonIcon.tsx",
      "components/Button/ButtonText.tsx",
      "components/Button/index.ts",
      "components/Button/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "button-group": {
    "files": [
      "components/ButtonGroup/ButtonGroup.tsx",
      "components/ButtonGroup/index.ts",
      "components/ButtonGroup/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "card": {
    "files": [
      "components/Card/Card.tsx",
      "components/Card/CardContent.tsx",
      "components/Card/CardFooter.tsx",
      "components/Card/CardHeader.tsx",
      "components/Card/CardMedia.tsx",
      "components/Card/hooks.ts",
      "components/Card/index.ts",
      "components/Card/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "carousel": {
    "files": [
      "components/Button/Button.tsx",
      "components/Button/ButtonBadge.tsx",
      "components/Button/ButtonIcon.tsx",
      "components/Button/ButtonText.tsx",
      "components/Button/index.ts",
      "components/Button/types.ts",
      "components/Carousel/Carousel.tsx",
      "components/Carousel/CarouselBullets.tsx",
      "components/Carousel/CarouselGallery.tsx",
      "components/Carousel/CarouselNext.tsx",
      "components/Carousel/CarouselPlayPause.tsx",
      "components/Carousel/CarouselPrevious.tsx",
      "components/Carousel/CarouselSlide.tsx",
      "components/Carousel/CarouselSpeedControl.tsx",
      "components/Carousel/CarouselViewport.tsx",
      "components/Carousel/hooks.ts",
      "components/Carousel/index.ts",
      "components/Carousel/types.ts",
      "components/Popover/Popover.tsx",
      "components/Popover/PopoverContent.tsx",
      "components/Popover/PopoverTrigger.tsx",
      "components/Popover/hooks.ts",
      "components/Popover/index.ts",
      "components/Popover/types.ts",
      "hooks/useKeyPress.ts",
      "hooks/useMediaQuery.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "button",
      "popover",
      "use-key-press",
      "use-media-query",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "checkbox": {
    "files": [
      "components/CheckBox/CheckBox.tsx",
      "components/CheckBox/CheckBoxDescription.tsx",
      "components/CheckBox/CheckBoxError.tsx",
      "components/CheckBox/CheckBoxIndicator.tsx",
      "components/CheckBox/CheckBoxLabel.tsx",
      "components/CheckBox/hooks.ts",
      "components/CheckBox/index.ts",
      "components/CheckBox/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "collapsible": {
    "files": [
      "components/Collapsible/Collapsible.tsx",
      "components/Collapsible/CollapsibleContent.tsx",
      "components/Collapsible/CollapsibleTrigger.tsx",
      "components/Collapsible/index.ts",
      "components/Collapsible/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "color-picker": {
    "files": [
      "components/ColorPicker/ColorPicker.tsx",
      "components/ColorPicker/ColorPickerContent.tsx",
      "components/ColorPicker/ColorPickerCopyButton.tsx",
      "components/ColorPicker/ColorPickerDescription.tsx",
      "components/ColorPicker/ColorPickerError.tsx",
      "components/ColorPicker/ColorPickerEyeDropper.tsx",
      "components/ColorPicker/ColorPickerInput.tsx",
      "components/ColorPicker/ColorPickerLabel.tsx",
      "components/ColorPicker/ColorPickerPalette.tsx",
      "components/ColorPicker/ColorPickerPresets.tsx",
      "components/ColorPicker/ColorPickerSwatches.tsx",
      "components/ColorPicker/ColorPickerTrigger.tsx",
      "components/ColorPicker/hooks.ts",
      "components/ColorPicker/index.ts",
      "components/ColorPicker/types.ts",
      "components/ColorPicker/utils.ts",
      "hooks/useKeyPress.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-key-press",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "command-box": {
    "files": [
      "components/CommandBox/CommandBox.tsx",
      "components/CommandBox/CommandBoxEmpty.tsx",
      "components/CommandBox/CommandBoxGroup.tsx",
      "components/CommandBox/CommandBoxInput.tsx",
      "components/CommandBox/CommandBoxItem.tsx",
      "components/CommandBox/CommandBoxList.tsx",
      "components/CommandBox/CommandBoxOverlay.tsx",
      "components/CommandBox/CommandBoxSeparator.tsx",
      "components/CommandBox/hooks.ts",
      "components/CommandBox/index.ts",
      "components/CommandBox/types.ts",
      "hooks/useKeyPress.ts",
      "hooks/useLockBodyScroll.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-key-press",
      "use-lock-body-scroll",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "date-picker": {
    "files": [
      "components/DatePicker/DatePicker.tsx",
      "components/DatePicker/DatePickerCalendar.tsx",
      "components/DatePicker/DatePickerDropDowns.tsx",
      "components/DatePicker/DatePickerFooter.tsx",
      "components/DatePicker/DatePickerIcons.tsx",
      "components/DatePicker/DatePickerTrigger.tsx",
      "components/DatePicker/index.ts",
      "components/DatePicker/types.ts",
      "components/DatePicker/utils.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "moment",
        "version": "^2.30.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "divider": {
    "files": [
      "components/Divider/Divider.tsx",
      "components/Divider/DividerLabel.tsx",
      "components/Divider/DividerLine.tsx",
      "components/Divider/index.ts",
      "components/Divider/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "draggable": {
    "files": [
      "components/Draggable/Draggable.tsx",
      "components/Draggable/DraggableContainer.tsx",
      "components/Draggable/DraggableDropIndicator.tsx",
      "components/Draggable/DraggableHandle.tsx",
      "components/Draggable/DraggableItem.tsx",
      "components/Draggable/DraggablePlaceholder.tsx",
      "components/Draggable/DraggablePreview.tsx",
      "components/Draggable/hooks.ts",
      "components/Draggable/index.ts",
      "components/Draggable/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "drawer": {
    "files": [
      "components/Drawer/Drawer.tsx",
      "components/Drawer/DrawerClose.tsx",
      "components/Drawer/DrawerContent.tsx",
      "components/Drawer/DrawerDescription.tsx",
      "components/Drawer/DrawerFooter.tsx",
      "components/Drawer/DrawerHeader.tsx",
      "components/Drawer/DrawerOverlay.tsx",
      "components/Drawer/DrawerPortal.tsx",
      "components/Drawer/DrawerTitle.tsx",
      "components/Drawer/DrawerTrigger.tsx",
      "components/Drawer/index.ts",
      "components/Drawer/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "file-upload": {
    "files": [
      "components/FileUpload/DropZone.tsx",
      "components/FileUpload/DropZoneContent.tsx",
      "components/FileUpload/FileUpload.tsx",
      "components/FileUpload/FileUploadActions.tsx",
      "components/FileUpload/FileUploadErrorMessage.tsx",
      "components/FileUpload/FileUploadItem.tsx",
      "components/FileUpload/FileUploadList.tsx",
      "components/FileUpload/hooks.ts",
      "components/FileUpload/index.ts",
      "components/FileUpload/types.ts",
      "components/FileUpload/utils.tsx"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "floating-dock": {
    "files": [
      "components/Divider/Divider.tsx",
      "components/Divider/DividerLabel.tsx",
      "components/Divider/DividerLine.tsx",
      "components/Divider/index.ts",
      "components/Divider/types.ts",
      "components/FloatingDock/FloatingDock.tsx",
      "components/FloatingDock/FloatingDockContainer.tsx",
      "components/FloatingDock/FloatingDockItem.tsx",
      "components/FloatingDock/FloatingDockLogo.tsx",
      "components/FloatingDock/index.ts",
      "components/FloatingDock/types.ts",
      "components/Tooltip/Tooltip.tsx",
      "components/Tooltip/index.ts",
      "components/Tooltip/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "divider",
      "tooltip"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "footer": {
    "files": [
      "components/Footer/Footer.tsx",
      "components/Footer/FooterContent.tsx",
      "components/Footer/FooterLayout.tsx",
      "components/Footer/FooterRoot.tsx",
      "components/Footer/FooterSocial.tsx",
      "components/Footer/FooterUtilities.tsx",
      "components/Footer/index.ts",
      "components/Footer/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "grid-layout": {
    "files": [
      "components/GridLayout/GridDragHandle.tsx",
      "components/GridLayout/GridItem.tsx",
      "components/GridLayout/GridLayout.tsx",
      "components/GridLayout/GridLayoutContainer.tsx",
      "components/GridLayout/GridPlaceholder.tsx",
      "components/GridLayout/GridResizeHandle.tsx",
      "components/GridLayout/algorithms.ts",
      "components/GridLayout/hooks.ts",
      "components/GridLayout/index.ts",
      "components/GridLayout/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "hover-card": {
    "files": [
      "components/HoverCard/HoverCard.tsx",
      "components/HoverCard/HoverCardArrow.tsx",
      "components/HoverCard/hooks.ts",
      "components/HoverCard/index.ts",
      "components/HoverCard/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "marquee": {
    "files": [
      "components/Marquee/Marquee.tsx",
      "components/Marquee/MarqueeItem.tsx",
      "components/Marquee/index.ts",
      "components/Marquee/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "menubar": {
    "files": [
      "components/MenuBar/Menu.tsx",
      "components/MenuBar/MenuBar.tsx",
      "components/MenuBar/MenubarCheckBoxItem.tsx",
      "components/MenuBar/MenubarItem.tsx",
      "components/MenuBar/MenubarLabel.tsx",
      "components/MenuBar/MenubarPortal.tsx",
      "components/MenuBar/MenubarRadioGroup.tsx",
      "components/MenuBar/MenubarSeparator.tsx",
      "components/MenuBar/MenubarSubMenu.tsx",
      "components/MenuBar/hooks.ts",
      "components/MenuBar/index.ts",
      "components/MenuBar/types.ts",
      "hooks/useElementPosition.ts",
      "hooks/useKeyPress.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-element-position",
      "use-key-press",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "modal": {
    "files": [
      "components/Modal/Modal.tsx",
      "components/Modal/ModalBody.tsx",
      "components/Modal/ModalClose.tsx",
      "components/Modal/ModalContent.tsx",
      "components/Modal/ModalDescription.tsx",
      "components/Modal/ModalFooter.tsx",
      "components/Modal/ModalHeader.tsx",
      "components/Modal/ModalOverlay.tsx",
      "components/Modal/ModalTitle.tsx",
      "components/Modal/ModalTrigger.tsx",
      "components/Modal/index.ts",
      "components/Modal/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "navbar": {
    "files": [
      "components/NavBar/NavBar.tsx",
      "components/NavBar/NavBarActions.tsx",
      "components/NavBar/NavBarBrand.tsx",
      "components/NavBar/NavBarMobileMenu.tsx",
      "components/NavBar/NavBarSeparator.tsx",
      "components/NavBar/NavBarToggle.tsx",
      "components/NavBar/NavbarContainer.tsx",
      "components/NavBar/NavbarMenuItems.tsx",
      "components/NavBar/index.ts",
      "components/NavBar/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "otp-input": {
    "files": [
      "components/OTPInput/OTPInput.tsx",
      "components/OTPInput/OTPInputGroup.tsx",
      "components/OTPInput/OTPInputSlot.tsx",
      "components/OTPInput/OTPSeparator.tsx",
      "components/OTPInput/index.ts",
      "components/OTPInput/types.ts",
      "utils/input-styles.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "pagination": {
    "files": [
      "components/Pagination/CompactPagination.tsx",
      "components/Pagination/Pagination.tsx",
      "components/Pagination/PaginationButtons.tsx",
      "components/Pagination/PaginationInfo.tsx",
      "components/Pagination/PaginationRoot.tsx",
      "components/Pagination/index.ts",
      "components/Pagination/types.ts",
      "components/Pagination/utils.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "popover": {
    "files": [
      "components/Button/Button.tsx",
      "components/Button/ButtonBadge.tsx",
      "components/Button/ButtonIcon.tsx",
      "components/Button/ButtonText.tsx",
      "components/Button/index.ts",
      "components/Button/types.ts",
      "components/Popover/Popover.tsx",
      "components/Popover/PopoverContent.tsx",
      "components/Popover/PopoverTrigger.tsx",
      "components/Popover/hooks.ts",
      "components/Popover/index.ts",
      "components/Popover/types.ts",
      "hooks/useKeyPress.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "button",
      "use-key-press",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "radio-group": {
    "files": [
      "components/RadioGroup/RadioGroup.tsx",
      "components/RadioGroup/RadioItem.tsx",
      "components/RadioGroup/hooks.ts",
      "components/RadioGroup/index.ts",
      "components/RadioGroup/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "rate": {
    "files": [
      "components/Rate/Rate.tsx",
      "components/Rate/RateContainer.tsx",
      "components/Rate/RateDescription.tsx",
      "components/Rate/RateErrorText.tsx",
      "components/Rate/RateLabel.tsx",
      "components/Rate/RateStars.tsx",
      "components/Rate/RateValue.tsx",
      "components/Rate/hooks.ts",
      "components/Rate/index.ts",
      "components/Rate/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "resizable-pane": {
    "files": [
      "components/ResizablePane/ResizablePane.tsx",
      "components/ResizablePane/ResizablePaneHandle.tsx",
      "components/ResizablePane/ResizablePanel.tsx",
      "components/ResizablePane/index.ts",
      "components/ResizablePane/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "sidebar": {
    "files": [
      "components/Sidebar/Sidebar.tsx",
      "components/Sidebar/SidebarContent.tsx",
      "components/Sidebar/SidebarFooter.tsx",
      "components/Sidebar/SidebarHeader.tsx",
      "components/Sidebar/SidebarMenu.tsx",
      "components/Sidebar/SidebarMenuItem.tsx",
      "components/Sidebar/SidebarMobileMenuButton.tsx",
      "components/Sidebar/SidebarToggle.tsx",
      "components/Sidebar/hooks.ts",
      "components/Sidebar/index.ts",
      "components/Sidebar/types.ts",
      "components/Tooltip/Tooltip.tsx",
      "components/Tooltip/index.ts",
      "components/Tooltip/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "tooltip"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "skeleton": {
    "files": [
      "components/Skeleton/SkeletonComposites.tsx",
      "components/Skeleton/SkeletonItem.tsx",
      "components/Skeleton/SkeletonPrimitives.tsx",
      "components/Skeleton/SkeletonRoot.tsx",
      "components/Skeleton/config.ts",
      "components/Skeleton/index.ts",
      "components/Skeleton/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "slider": {
    "files": [
      "components/Slider/Slider.tsx",
      "components/Slider/SliderThumb.tsx",
      "components/Slider/SliderTrack.tsx",
      "components/Slider/hooks.ts",
      "components/Slider/index.ts",
      "components/Slider/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "spinner": {
    "files": [
      "components/Spinner/Spinner.tsx",
      "components/Spinner/index.ts",
      "components/Spinner/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "stepper": {
    "files": [
      "components/Stepper/Stepper.tsx",
      "components/Stepper/StepperContent.tsx",
      "components/Stepper/StepperIndicator.tsx",
      "components/Stepper/hooks.ts",
      "components/Stepper/index.ts",
      "components/Stepper/step.tsx",
      "components/Stepper/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "switch": {
    "files": [
      "components/Switch/Switch.tsx",
      "components/Switch/SwitchLabel.tsx",
      "components/Switch/SwitchTrack.tsx",
      "components/Switch/hooks.ts",
      "components/Switch/index.ts",
      "components/Switch/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "tab": {
    "files": [
      "components/Tab/Tab.tsx",
      "components/Tab/TabsContent.tsx",
      "components/Tab/TabsList.tsx",
      "components/Tab/TabsTrigger.tsx",
      "components/Tab/hooks.ts",
      "components/Tab/index.ts",
      "components/Tab/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "table": {
    "files": [
      "components/Table/Table.tsx",
      "components/Table/TableBody.tsx",
      "components/Table/TableCaption.tsx",
      "components/Table/TableCell.tsx",
      "components/Table/TableFooter.tsx",
      "components/Table/TableHead.tsx",
      "components/Table/TableHeader.tsx",
      "components/Table/TableRow.tsx",
      "components/Table/index.ts",
      "components/Table/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "text-area": {
    "files": [
      "components/TextArea/TextArea.tsx",
      "components/TextArea/TextAreaCharCount.tsx",
      "components/TextArea/TextAreaErrorText.tsx",
      "components/TextArea/TextAreaInput.tsx",
      "components/TextArea/TextAreaLabel.tsx",
      "components/TextArea/TextAreaSupportText.tsx",
      "components/TextArea/index.ts",
      "components/TextArea/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "text-input": {
    "files": [
      "components/TextInput/Input.tsx",
      "components/TextInput/TextInput.tsx",
      "components/TextInput/TextInputCharacterCount.tsx",
      "components/TextInput/TextInputClearButton.tsx",
      "components/TextInput/TextInputDescription.tsx",
      "components/TextInput/TextInputErrorMessage.tsx",
      "components/TextInput/TextInputField.tsx",
      "components/TextInput/TextInputIcon.tsx",
      "components/TextInput/TextInputLabel.tsx",
      "components/TextInput/TextInputLoadingSpinner.tsx",
      "components/TextInput/TextInputNumberInput.tsx",
      "components/TextInput/TextInputPasswordInput.tsx",
      "components/TextInput/TextInputSearchInput.tsx",
      "components/TextInput/TextInputSuccessMessage.tsx",
      "components/TextInput/TextInputWarningMessage.tsx",
      "components/TextInput/index.ts",
      "components/TextInput/number-format.ts",
      "components/TextInput/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "toaster": {
    "files": [
      "components/Toaster/ToastContainer.tsx",
      "components/Toaster/ToastIcons.tsx",
      "components/Toaster/ToastItem.tsx",
      "components/Toaster/ToastProvider.tsx",
      "components/Toaster/ToastStack.tsx",
      "components/Toaster/ToastUtilities.tsx",
      "components/Toaster/constants.ts",
      "components/Toaster/index.ts",
      "components/Toaster/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "tooltip": {
    "files": [
      "components/Tooltip/Tooltip.tsx",
      "components/Tooltip/index.ts",
      "components/Tooltip/types.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "tour": {
    "files": [
      "components/Tour/Tour.tsx",
      "components/Tour/TourOverlay.tsx",
      "components/Tour/TourPopover.tsx",
      "components/Tour/hooks.ts",
      "components/Tour/index.ts",
      "components/Tour/types.ts",
      "components/Tour/use-position.ts",
      "components/Tour/use-target.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "typography": {
    "files": [
      "components/Typography/Typography.tsx",
      "components/Typography/TypographyCode.tsx",
      "components/Typography/TypographyHeadings.tsx",
      "components/Typography/TypographyLink.tsx",
      "components/Typography/TypographyTextElements.tsx",
      "components/Typography/index.ts",
      "components/Typography/types.ts",
      "components/Typography/utils.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "audio-player": {
    "files": [
      "components/AudioPlayer/Audio.tsx",
      "components/AudioPlayer/AudioControls.tsx",
      "components/AudioPlayer/AudioPlaylist.tsx",
      "components/AudioPlayer/AudioProgress.tsx",
      "components/AudioPlayer/AudioRate.tsx",
      "components/AudioPlayer/AudioStatus.tsx",
      "components/AudioPlayer/AudioTrackInfo.tsx",
      "components/AudioPlayer/AudioVolume.tsx",
      "components/AudioPlayer/index.ts",
      "components/AudioPlayer/types.ts",
      "components/AudioPlayer/utils.ts",
      "components/Button/Button.tsx",
      "components/Button/ButtonBadge.tsx",
      "components/Button/ButtonIcon.tsx",
      "components/Button/ButtonText.tsx",
      "components/Button/index.ts",
      "components/Button/types.ts",
      "components/Popover/Popover.tsx",
      "components/Popover/PopoverContent.tsx",
      "components/Popover/PopoverTrigger.tsx",
      "components/Popover/hooks.ts",
      "components/Popover/index.ts",
      "components/Popover/types.ts",
      "components/Slider/Slider.tsx",
      "components/Slider/SliderThumb.tsx",
      "components/Slider/SliderTrack.tsx",
      "components/Slider/hooks.ts",
      "components/Slider/index.ts",
      "components/Slider/types.ts",
      "hooks/useKeyPress.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "button",
      "popover",
      "slider",
      "use-key-press",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "hls.js",
        "version": "^1.6.15"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "big-calendar": {
    "files": [
      "components/BigCalendar/BigCalendar.tsx",
      "components/BigCalendar/BigCalendarDayView.tsx",
      "components/BigCalendar/BigCalendarEvent.tsx",
      "components/BigCalendar/BigCalendarMonthView.tsx",
      "components/BigCalendar/BigCalendarToolbar.tsx",
      "components/BigCalendar/BigCalendarWeekView.tsx",
      "components/BigCalendar/hooks.ts",
      "components/BigCalendar/index.ts",
      "components/BigCalendar/types.ts",
      "components/BigCalendar/utils.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "context-menu": {
    "files": [
      "components/ContextMenu/ContextMenu.tsx",
      "components/ContextMenu/ContextMenuCheckBoxItem.tsx",
      "components/ContextMenu/ContextMenuContent.tsx",
      "components/ContextMenu/ContextMenuItem.tsx",
      "components/ContextMenu/ContextMenuLabel.tsx",
      "components/ContextMenu/ContextMenuRadioGroup.tsx",
      "components/ContextMenu/ContextMenuSeparator.tsx",
      "components/ContextMenu/ContextMenuSub.tsx",
      "components/ContextMenu/ContextMenuTrigger.tsx",
      "components/ContextMenu/hooks.ts",
      "components/ContextMenu/index.ts",
      "components/ContextMenu/types.ts",
      "hooks/useLockBodyScroll.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-lock-body-scroll",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "qrcode": {
    "files": [
      "components/QRcode/QRCode.tsx",
      "components/QRcode/QREncoder.ts",
      "components/QRcode/index.ts",
      "components/QRcode/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "class-variance-authority",
        "version": "^0.7.0"
      },
      {
        "name": "clsx",
        "version": "^2.1.1"
      }
    ]
  },
  "select": {
    "files": [
      "components/Select/Select.tsx",
      "components/Select/SelectContent.tsx",
      "components/Select/SelectCreateButton.tsx",
      "components/Select/SelectOptionList.tsx",
      "components/Select/SelectStates.tsx",
      "components/Select/SelectTrigger.tsx",
      "components/Select/Selectitem.tsx",
      "components/Select/index.ts",
      "components/Select/types.ts",
      "hooks/useKeyPress.ts",
      "hooks/useLockBodyScroll.ts",
      "hooks/useOnClickOutside.ts",
      "utils/index.ts",
      "utils/input-styles.ts",
      "utils/use-merge-refs.ts"
    ],
    "registryDependencies": [
      "use-key-press",
      "use-lock-body-scroll",
      "use-on-click-outside"
    ],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      },
      {
        "name": "tailwind-merge",
        "version": "^3.5.0"
      }
    ]
  },
  "show": {
    "files": [
      "components/Show/Match.tsx",
      "components/Show/Show.tsx",
      "components/Show/index.ts",
      "components/Show/types.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "time-picker": {
    "files": [
      "components/TimePicker/TimePicker.tsx",
      "components/TimePicker/TimePickerColumns.tsx",
      "components/TimePicker/TimePickerContent.tsx",
      "components/TimePicker/TimePickerFooter.tsx",
      "components/TimePicker/TimePickerTrigger.tsx",
      "components/TimePicker/index.ts",
      "components/TimePicker/types.ts",
      "components/TimePicker/utils.ts",
      "utils/input-styles.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "tree": {
    "files": [
      "components/Tree/Tree.tsx",
      "components/Tree/TreeActions.tsx",
      "components/Tree/TreeContainer.tsx",
      "components/Tree/TreeNode.tsx",
      "components/Tree/TreeSearch.tsx",
      "components/Tree/hooks.ts",
      "components/Tree/index.ts",
      "components/Tree/types.ts",
      "components/Tree/utils.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "lucide-react",
        "version": "^0.577.0"
      }
    ]
  },
  "video-player": {
    "files": [
      "components/VideoPlayer/Video.tsx",
      "components/VideoPlayer/VideoPlayer.tsx",
      "components/VideoPlayer/VideoPlayerAdvanced.tsx",
      "components/VideoPlayer/VideoPlayerControls.tsx",
      "components/VideoPlayer/VideoPlayerPlayback.tsx",
      "components/VideoPlayer/VideoPlayerPlaylist.tsx",
      "components/VideoPlayer/VideoPlayerProgress.tsx",
      "components/VideoPlayer/VideoPlayerStatus.tsx",
      "components/VideoPlayer/VideoPlayerVolume.tsx",
      "components/VideoPlayer/index.ts",
      "components/VideoPlayer/types.ts",
      "components/VideoPlayer/utils.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": [
      {
        "name": "clsx",
        "version": "^2.1.1"
      },
      {
        "name": "hls.js",
        "version": "^1.6.15"
      }
    ]
  },
  "use-battery-status": {
    "files": [
      "hooks/useBatteryStatus.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-confirm-exit": {
    "files": [
      "hooks/useConfirmExit.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-copy-to-clipboard": {
    "files": [
      "hooks/useCopyToClipboard.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-debounce": {
    "files": [
      "hooks/useDebounce.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-device-os": {
    "files": [
      "hooks/useDeviceOS.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-element-position": {
    "files": [
      "hooks/useElementPosition.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-hover": {
    "files": [
      "hooks/useHover.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-idle": {
    "files": [
      "hooks/useIdle.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-indexed-db": {
    "files": [
      "hooks/useIndexedDB.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-interval-when": {
    "files": [
      "hooks/useIntervalWhen.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-key-press": {
    "files": [
      "hooks/useKeyPress.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-list": {
    "files": [
      "hooks/useList.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-lock-body-scroll": {
    "files": [
      "hooks/useLockBodyScroll.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-local-storage": {
    "files": [
      "hooks/useLocalStorage.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-map": {
    "files": [
      "hooks/useMap.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-measure": {
    "files": [
      "hooks/useMeasure.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-media-query": {
    "files": [
      "hooks/useMediaQuery.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-mouse-track": {
    "files": [
      "hooks/useMouseTrack.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-network-status": {
    "files": [
      "hooks/useNetworkStatus.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-on-click-outside": {
    "files": [
      "hooks/useOnClickOutside.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-page-leave": {
    "files": [
      "hooks/usePageLeave.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-permission": {
    "files": [
      "hooks/usePermission.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-previous-state": {
    "files": [
      "hooks/usePreviousState.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-queue": {
    "files": [
      "hooks/useQueue.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-render-count": {
    "files": [
      "hooks/useRenderCount.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-scroll-position": {
    "files": [
      "hooks/useScrollPosition.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-set": {
    "files": [
      "hooks/useSet.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-throttle": {
    "files": [
      "hooks/useThrottle.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-timeout": {
    "files": [
      "hooks/useTimeout.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-visibility-change": {
    "files": [
      "hooks/useVisibilityChange.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-window-size": {
    "files": [
      "hooks/useWindowSize.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-countdown": {
    "files": [
      "hooks/useCountdown.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  },
  "use-in-view": {
    "files": [
      "components/Animation/types.ts",
      "hooks/useInView.ts"
    ],
    "registryDependencies": [
      "animation"
    ],
    "npmDependencies": []
  },
  "use-is-mount": {
    "files": [
      "hooks/useIsMount.ts"
    ],
    "registryDependencies": [],
    "npmDependencies": []
  }
};
export const publicExports: Record<string, string> = {
  "UseIndexedDBOptions": "use-indexed-db",
  "UseIndexedDBReturn": "use-indexed-db",
  "useIndexedDB": "use-indexed-db",
  "useMeasure": "use-measure",
  "useRenderCount": "use-render-count",
  "ScrollPosition": "use-scroll-position",
  "UseScrollPositionOptions": "use-scroll-position",
  "useScrollPosition": "use-scroll-position",
  "useMouseTrack": "use-mouse-track",
  "useSet": "use-set",
  "BatteryStatus": "use-battery-status",
  "useBatteryStatus": "use-battery-status",
  "NetworkStatus": "use-network-status",
  "useNetworkStatus": "use-network-status",
  "useWindowSize": "use-window-size",
  "usePreviousState": "use-previous-state",
  "usePageLeave": "use-page-leave",
  "UseCountdownOptions": "use-countdown",
  "useCountdown": "use-countdown",
  "useDebounce": "use-debounce",
  "useMap": "use-map",
  "useCopyToClipboard": "use-copy-to-clipboard",
  "useList": "use-list",
  "useLockBodyScroll": "use-lock-body-scroll",
  "OSName": "use-device-os",
  "BrowserName": "use-device-os",
  "DeviceType": "use-device-os",
  "DeviceOSInfo": "use-device-os",
  "useDeviceOS": "use-device-os",
  "useQueue": "use-queue",
  "useIntervalWhen": "use-interval-when",
  "useLocalStorage": "use-local-storage",
  "useTimeout": "use-timeout",
  "useVisibilityChange": "use-visibility-change",
  "useIdle": "use-idle",
  "useThrottle": "use-throttle",
  "useHover": "use-hover",
  "useIsMount": "use-is-mount",
  "useMediaQuery": "use-media-query",
  "useElementPosition": "use-element-position",
  "useOnClickOutside": "use-on-click-outside",
  "PermissionName": "use-permission",
  "PermissionState": "use-permission",
  "UsePermissionReturn": "use-permission",
  "usePermission": "use-permission",
  "UseConfirmExitOptions": "use-confirm-exit",
  "useConfirmExit": "use-confirm-exit",
  "matchesKeyCombo": "use-key-press",
  "useKeyPress": "use-key-press",
  "KeyTarget": "use-key-press",
  "KeyBinding": "use-key-press",
  "useInView": "use-in-view",
  "Badge": "badge",
  "BadgeProps": "badge",
  "BadgeVariant": "badge",
  "BadgeSize": "badge",
  "Checkbox": "checkbox",
  "CheckboxRootProps": "checkbox",
  "CheckboxIndicatorProps": "checkbox",
  "CheckboxLabelProps": "checkbox",
  "CheckboxDescriptionProps": "checkbox",
  "CheckboxErrorProps": "checkbox",
  "FloatingDock": "floating-dock",
  "DockBaseProps": "floating-dock",
  "DockItemProps": "floating-dock",
  "DockLogoProps": "floating-dock",
  "InjectedDockProps": "floating-dock",
  "Pagination": "pagination",
  "ResizablePane": "resizable-pane",
  "useResizablePane": "resizable-pane",
  "ResizeDirection": "resizable-pane",
  "Show": "show",
  "Match": "show",
  "Case": "show",
  "Default": "show",
  "ShowProps": "show",
  "MatchProps": "show",
  "CaseProps": "show",
  "DefaultProps": "show",
  "Spinner": "spinner",
  "SpinnerProps": "spinner",
  "SpinnerSize": "spinner",
  "Switch": "switch",
  "SwitchProps": "switch",
  "Tabs": "tab",
  "Table": "table",
  "TableBody": "table",
  "TableCaption": "table",
  "TableCell": "table",
  "TableFooter": "table",
  "TableHead": "table",
  "TableHeader": "table",
  "TableRow": "table",
  "TableProps": "table",
  "TableBodyProps": "table",
  "TableCaptionProps": "table",
  "TableCellProps": "table",
  "TableFooterProps": "table",
  "TableHeadProps": "table",
  "TableHeaderProps": "table",
  "TableRowProps": "table",
  "TextInput": "text-input",
  "useTextInput": "text-input",
  "Label": "text-input",
  "Field": "text-input",
  "Input": "text-input",
  "PasswordInput": "text-input",
  "NumberInput": "text-input",
  "SearchInput": "text-input",
  "Description": "text-input",
  "ErrorMessage": "text-input",
  "WarningMessage": "text-input",
  "SuccessMessage": "text-input",
  "Icon": "text-input",
  "LoadingSpinner": "text-input",
  "CharacterCount": "text-input",
  "ClearButton": "text-input",
  "InputSize": "text-input",
  "InputType": "text-input",
  "NumberType": "text-input",
  "TextInputContextValue": "text-input",
  "TextInputValidationState": "text-input",
  "Typography": "typography",
  "BaseTypographyProps": "typography",
  "H1Props": "typography",
  "H2Props": "typography",
  "H3Props": "typography",
  "H4Props": "typography",
  "H5Props": "typography",
  "H6Props": "typography",
  "PProps": "typography",
  "LabelProps": "typography",
  "LinkProps": "typography",
  "CodeProps": "typography",
  "CTAProps": "typography",
  "AccordionProps": "accordion",
  "AccordionItemProps": "accordion",
  "AccordionHeaderProps": "accordion",
  "AccordionBodyProps": "accordion",
  "AccordionContextType": "accordion",
  "Accordion": "accordion",
  "AccordionItem": "accordion",
  "AccordionHeader": "accordion",
  "AccordionBody": "accordion",
  "AffixPosition": "affix",
  "AffixProps": "affix",
  "Affix": "affix",
  "Alert": "alert",
  "AlertVariant": "alert",
  "AlertRootProps": "alert",
  "AlertIconProps": "alert",
  "AlertDismissProps": "alert",
  "Animation": "animation",
  "AnimationDuration": "animation",
  "AnimationDelay": "animation",
  "AnimationIteration": "animation",
  "AnimationDirection": "animation",
  "AnimationFillMode": "animation",
  "AnimationScale": "animation",
  "BaseAnimationProps": "animation",
  "DirectionalAnimationProps": "animation",
  "ScaleAnimationProps": "animation",
  "RotateAnimationProps": "animation",
  "AnimationVariant": "animation",
  "UseInViewOptions": "animation",
  "AnimateInViewProps": "animation",
  "AspectRatio": "aspectratio",
  "AspectRatioPreset": "aspectratio",
  "AspectRatioProps": "aspectratio",
  "AudioPlayer": "audio-player",
  "Track": "audio-player",
  "AudioPlayerState": "audio-player",
  "AudioPlayerActions": "audio-player",
  "AudioPlayerGetters": "audio-player",
  "RootProps": "audio-player",
  "PropGetter": "audio-player",
  "Avatar": "avatar",
  "AvatarSize": "avatar",
  "AvatarStatus": "avatar",
  "AvatarRootProps": "avatar",
  "AvatarImageProps": "avatar",
  "AvatarInitialsProps": "avatar",
  "AvatarStatusProps": "avatar",
  "AvatarFallbackProps": "avatar",
  "AvatarGroup": "avatar-group",
  "AvatarGroupSize": "avatar-group",
  "AvatarGroupLayout": "avatar-group",
  "UserData": "avatar-group",
  "AvatarGroupProps": "avatar-group",
  "CalendarView": "big-calendar",
  "CalendarEvent": "big-calendar",
  "BigCalendarProps": "big-calendar",
  "BigCalendarEventProps": "big-calendar",
  "BigCalendar": "big-calendar",
  "Breadcrumb": "breadcrumb",
  "BreadcrumbList": "breadcrumb",
  "BreadcrumbItem": "breadcrumb",
  "BreadcrumbLink": "breadcrumb",
  "BreadcrumbPage": "breadcrumb",
  "BreadcrumbSeparator": "breadcrumb",
  "BreadcrumbEllipsis": "breadcrumb",
  "BreadcrumbProps": "breadcrumb",
  "BreadcrumbListProps": "breadcrumb",
  "BreadcrumbItemProps": "breadcrumb",
  "BreadcrumbLinkProps": "breadcrumb",
  "BreadcrumbPageProps": "breadcrumb",
  "BreadcrumbSeparatorProps": "breadcrumb",
  "BreadcrumbEllipsisProps": "breadcrumb",
  "Status": "button",
  "BadgePosition": "button",
  "ButtonProps": "button",
  "ButtonSize": "button",
  "ButtonVariant": "button",
  "IconProps": "button",
  "TextProps": "button",
  "Button": "button",
  "ButtonGroup": "button-group",
  "ButtonGroupProps": "button-group",
  "ButtonGroupRadius": "button-group",
  "CardProps": "card",
  "CardHeaderProps": "card",
  "CardMediaProps": "card",
  "CardContentProps": "card",
  "CardFooterProps": "card",
  "CardHeader": "card",
  "CardMedia": "card",
  "CardContent": "card",
  "CardFooter": "card",
  "Card": "card",
  "SpeedMultiplier": "carousel",
  "ResponsiveItemsPerSlide": "carousel",
  "ItemsPerSlide": "carousel",
  "GalleryItem": "carousel",
  "CarouselContextValue": "carousel",
  "CarouselProps": "carousel",
  "CarouselViewportProps": "carousel",
  "CarouselSlideProps": "carousel",
  "CarouselNavigationProps": "carousel",
  "CarouselBulletsProps": "carousel",
  "CarouselPlayPauseProps": "carousel",
  "CarouselSpeedControlProps": "carousel",
  "CarouselGalleryProps": "carousel",
  "Carousel": "carousel",
  "CollapsibleRootProps": "collapsible",
  "CollapsibleContentProps": "collapsible",
  "CollapsibleTriggerProps": "collapsible",
  "CollapsibleContextType": "collapsible",
  "Collapsible": "collapsible",
  "ColorFormat": "color-picker",
  "ValidationState": "color-picker",
  "ColorPickerContextValue": "color-picker",
  "RGB": "color-picker",
  "HSL": "color-picker",
  "ColorPickerRootProps": "color-picker",
  "ColorPickerLabelProps": "color-picker",
  "ColorPickerDescriptionProps": "color-picker",
  "ColorPickerErrorProps": "color-picker",
  "ColorPickerTriggerProps": "color-picker",
  "ColorPickerInputProps": "color-picker",
  "ColorPickerCopyButtonProps": "color-picker",
  "ColorPickerContentProps": "color-picker",
  "ColorPickerPaletteProps": "color-picker",
  "ColorPickerEyedropperProps": "color-picker",
  "ColorPickerPresetsProps": "color-picker",
  "ColorPickerSwatchesProps": "color-picker",
  "useColorPicker": "color-picker",
  "parseColor": "color-picker",
  "formatColor": "color-picker",
  "isValidColor": "color-picker",
  "ColorPicker": "color-picker",
  "CommandBox": "command-box",
  "CommandBoxRootProps": "command-box",
  "CommandBoxItemData": "command-box",
  "CommandBoxInputProps": "command-box",
  "CommandBoxListProps": "command-box",
  "CommandBoxItemProps": "command-box",
  "CommandBoxGroupProps": "command-box",
  "CommandBoxEmptyProps": "command-box",
  "CommandBoxSeparatorProps": "command-box",
  "CommandBoxOverlayProps": "command-box",
  "ContextMenuProps": "context-menu",
  "ContextMenuTriggerProps": "context-menu",
  "ContextMenuContentProps": "context-menu",
  "ContextMenuItemProps": "context-menu",
  "ContextMenuCheckboxItemProps": "context-menu",
  "ContextMenuRadioGroupProps": "context-menu",
  "ContextMenuRadioItemProps": "context-menu",
  "ContextMenuSubProps": "context-menu",
  "ContextMenuSubTriggerProps": "context-menu",
  "ContextMenuSubContentProps": "context-menu",
  "ContextMenuSeparatorProps": "context-menu",
  "ContextMenuLabelProps": "context-menu",
  "ContextMenu": "context-menu",
  "DatePicker": "date-picker",
  "DatePickerRoot": "date-picker",
  "DatePickerTrigger": "date-picker",
  "DatePickerCalendar": "date-picker",
  "DatePickerCalendarFooter": "date-picker",
  "DatePickerMode": "date-picker",
  "DateRange": "date-picker",
  "DatePickerValue": "date-picker",
  "DatePickerRootProps": "date-picker",
  "DatePickerTriggerProps": "date-picker",
  "DatePickerCalendarProps": "date-picker",
  "DatePickerCalendarFooterProps": "date-picker",
  "Divider": "divider",
  "DividerColor": "divider",
  "DividerLabelProps": "divider",
  "DividerLineProps": "divider",
  "DividerOrientation": "divider",
  "DividerRootProps": "divider",
  "DividerSize": "divider",
  "DividerSpacing": "divider",
  "DividerVariant": "divider",
  "Draggable": "draggable",
  "DraggableRootProps": "draggable",
  "DraggableContainerProps": "draggable",
  "DraggableItemProps": "draggable",
  "DraggableHandleProps": "draggable",
  "DraggablePreviewProps": "draggable",
  "DraggablePlaceholderProps": "draggable",
  "DraggableDropIndicatorProps": "draggable",
  "DraggableContextValue": "draggable",
  "ContainersMap": "draggable",
  "DrawerSide": "drawer",
  "DrawerContextType": "drawer",
  "DrawerRootProps": "drawer",
  "DrawerTriggerProps": "drawer",
  "DrawerOverlayProps": "drawer",
  "DrawerContentProps": "drawer",
  "DrawerCloseProps": "drawer",
  "DrawerTrigger": "drawer",
  "DrawerOverlay": "drawer",
  "DrawerContent": "drawer",
  "DrawerHeader": "drawer",
  "DrawerFooter": "drawer",
  "DrawerTitle": "drawer",
  "DrawerDescription": "drawer",
  "DrawerClose": "drawer",
  "DrawerPortal": "drawer",
  "Drawer": "drawer",
  "DrawerHeaderProps": "drawer",
  "FileWithMeta": "file-upload",
  "FileUpload": "file-upload",
  "GridLayout": "grid-layout",
  "GridLayoutRootProps": "grid-layout",
  "GridContainerProps": "grid-layout",
  "GridItemProps": "grid-layout",
  "GridDragHandleProps": "grid-layout",
  "GridResizeHandleProps": "grid-layout",
  "GridPlaceholderProps": "grid-layout",
  "GridLayoutItem": "grid-layout",
  "GridLayoutContextValue": "grid-layout",
  "Breakpoints": "grid-layout",
  "ResponsiveBreakpoint": "grid-layout",
  "Footer": "footer",
  "FooterVariant": "footer",
  "FooterRootProps": "footer",
  "FooterSectionProps": "footer",
  "FooterLinkProps": "footer",
  "FooterLogoProps": "footer",
  "FooterSocialProps": "footer",
  "FooterCopyrightProps": "footer",
  "FooterDividerProps": "footer",
  "HoverCard": "hover-card",
  "HoverCardProps": "hover-card",
  "HoverCardSide": "hover-card",
  "HoverCardAlign": "hover-card",
  "Marquee": "marquee",
  "MarqueeItem": "marquee",
  "MarqueeProps": "marquee",
  "MarqueeItemProps": "marquee",
  "MarqueeSpeed": "marquee",
  "MarqueeDirection": "marquee",
  "MarqueeLoopMode": "marquee",
  "Orientation": "menubar",
  "MenubarProps": "menubar",
  "MenuProps": "menubar",
  "MenuItemProps": "menubar",
  "MenuSeparatorProps": "menubar",
  "MenuLabelProps": "menubar",
  "MenuCheckboxItemProps": "menubar",
  "MenuRadioGroupProps": "menubar",
  "MenuRadioItemProps": "menubar",
  "Menubar": "menubar",
  "ModalSize": "modal",
  "ModalContextType": "modal",
  "ModalProps": "modal",
  "ModalTriggerProps": "modal",
  "ModalOverlayProps": "modal",
  "ModalContentProps": "modal",
  "ModalCloseProps": "modal",
  "ModalTrigger": "modal",
  "ModalOverlay": "modal",
  "ModalContent": "modal",
  "ModalHeader": "modal",
  "ModalBody": "modal",
  "ModalFooter": "modal",
  "ModalTitle": "modal",
  "ModalDescription": "modal",
  "ModalClose": "modal",
  "Modal": "modal",
  "ModalHeaderProps": "modal",
  "NavbarProps": "navbar",
  "NavbarContainerProps": "navbar",
  "NavbarBrandProps": "navbar",
  "NavbarItemsProps": "navbar",
  "NavbarItemProps": "navbar",
  "NavbarActionsProps": "navbar",
  "NavbarToggleProps": "navbar",
  "NavbarMobileMenuProps": "navbar",
  "NavbarMobileItemProps": "navbar",
  "NavbarContextValue": "navbar",
  "InjectedLinkProps": "navbar",
  "Navbar": "navbar",
  "OTPInputContextValue": "otp-input",
  "OTPInputRootProps": "otp-input",
  "OTPInputGroupProps": "otp-input",
  "OTPInputSlotProps": "otp-input",
  "OTPInputSeparatorProps": "otp-input",
  "OTPInputGroup": "otp-input",
  "OTPInputSlot": "otp-input",
  "OTPInputSeparator": "otp-input",
  "useOTPInput": "otp-input",
  "OTPInput": "otp-input",
  "PopoverProps": "popover",
  "PopoverTriggerProps": "popover",
  "PopoverContentProps": "popover",
  "Popover": "popover",
  "QRCode": "qrcode",
  "QRCodeProps": "qrcode",
  "QRCodeImageSettings": "qrcode",
  "ErrorCorrectionLevel": "qrcode",
  "RadioGroup": "radio-group",
  "RadioGroupProps": "radio-group",
  "RadioItemProps": "radio-group",
  "Rate": "rate",
  "RateContainerProps": "rate",
  "RateDescriptionProps": "rate",
  "RateErrorTextProps": "rate",
  "RateLabelProps": "rate",
  "RateRootProps": "rate",
  "RateSize": "rate",
  "RateStarProps": "rate",
  "RateStarsProps": "rate",
  "RateTextLabelProps": "rate",
  "RateValueProps": "rate",
  "Select": "select",
  "SelectRootProps": "select",
  "SelectTriggerProps": "select",
  "SelectContentProps": "select",
  "SelectItemProps": "select",
  "SelectLoadingProps": "select",
  "SelectNotFoundProps": "select",
  "SelectSearchHintProps": "select",
  "SelectCreateButtonProps": "select",
  "SelectErrorProps": "select",
  "SelectFooterProps": "select",
  "SelectAsyncOptionsProps": "select",
  "SelectListProps": "select",
  "OptionData": "select",
  "SelectValue": "select",
  "SingleValue": "select",
  "MultiValue": "select",
  "AsyncSearchProps": "select",
  "CreateableProps": "select",
  "SidebarProvider": "sidebar",
  "Sidebar": "sidebar",
  "SidebarHeader": "sidebar",
  "SidebarContent": "sidebar",
  "SidebarFooter": "sidebar",
  "SidebarMenu": "sidebar",
  "SidebarMenuGroup": "sidebar",
  "SidebarMenuItem": "sidebar",
  "SidebarToggle": "sidebar",
  "MobileMenuButton": "sidebar",
  "useSidebar": "sidebar",
  "SidebarContextType": "sidebar",
  "SidebarProviderProps": "sidebar",
  "SidebarProps": "sidebar",
  "SidebarHeaderProps": "sidebar",
  "SidebarHeaderChildren": "sidebar",
  "SidebarContentProps": "sidebar",
  "SidebarFooterProps": "sidebar",
  "SidebarFooterChildren": "sidebar",
  "SidebarMenuProps": "sidebar",
  "SidebarMenuGroupProps": "sidebar",
  "SidebarMenuItemProps": "sidebar",
  "SidebarToggleProps": "sidebar",
  "SubItem": "sidebar",
  "SkeletonAnimation": "skeleton",
  "SkeletonAvatarProps": "skeleton",
  "SkeletonCardProps": "skeleton",
  "SkeletonCircleProps": "skeleton",
  "SkeletonGridProps": "skeleton",
  "SkeletonGroupProps": "skeleton",
  "SkeletonItemProps": "skeleton",
  "SkeletonListProps": "skeleton",
  "SkeletonRectangleProps": "skeleton",
  "SkeletonRootProps": "skeleton",
  "SkeletonSize": "skeleton",
  "SkeletonTableProps": "skeleton",
  "SkeletonTextProps": "skeleton",
  "SkeletonVariant": "skeleton",
  "Skeleton": "skeleton",
  "SliderProps": "slider",
  "Slider": "slider",
  "Stepper": "stepper",
  "StepperRoot": "stepper",
  "Step": "stepper",
  "StepIndicator": "stepper",
  "StepContent": "stepper",
  "StepTitle": "stepper",
  "StepDescription": "stepper",
  "StepperOrientation": "stepper",
  "StepperStatus": "stepper",
  "StepperRootProps": "stepper",
  "StepProps": "stepper",
  "StepIndicatorProps": "stepper",
  "StepContentProps": "stepper",
  "StepTitleProps": "stepper",
  "StepDescriptionProps": "stepper",
  "TextAreaResize": "text-area",
  "TextAreaRootProps": "text-area",
  "TextAreaLabelProps": "text-area",
  "TextAreaInputProps": "text-area",
  "TextAreaSupportTextProps": "text-area",
  "TextAreaErrorTextProps": "text-area",
  "TextAreaCharCountProps": "text-area",
  "TextArea": "text-area",
  "TimeValue": "time-picker",
  "TimeRange": "time-picker",
  "TimeFormat": "time-picker",
  "TimepickerMode": "time-picker",
  "DisabledTimeConfig": "time-picker",
  "TimepickerContextValue": "time-picker",
  "TimepickerRootProps": "time-picker",
  "TimepickerTriggerProps": "time-picker",
  "TimepickerContentProps": "time-picker",
  "HourColumnProps": "time-picker",
  "MinuteColumnProps": "time-picker",
  "PeriodColumnProps": "time-picker",
  "TimeGridProps": "time-picker",
  "TimepickerFooterProps": "time-picker",
  "TimepickerErrorProps": "time-picker",
  "TimepickerTrigger": "time-picker",
  "TimepickerContent": "time-picker",
  "HourColumn": "time-picker",
  "MinuteColumn": "time-picker",
  "PeriodColumn": "time-picker",
  "TimeGrid": "time-picker",
  "TimepickerFooter": "time-picker",
  "TimepickerError": "time-picker",
  "Timepicker": "time-picker",
  "Toast": "toaster",
  "ToastProvider": "toaster",
  "useToast": "toaster",
  "ToastOptions": "toaster",
  "ToastType": "toaster",
  "ToastPosition": "toaster",
  "ToastContextType": "toaster",
  "ToastData": "toaster",
  "Tooltip": "tooltip",
  "TooltipPosition": "tooltip",
  "TooltipProps": "tooltip",
  "TooltipVariant": "tooltip",
  "TourStep": "tour",
  "TourContextValue": "tour",
  "TourProps": "tour",
  "Tour": "tour",
  "useTour": "tour",
  "Tree": "tree",
  "useTree": "tree",
  "CheckboxState": "tree",
  "TreeActionsProps": "tree",
  "TreeContainerProps": "tree",
  "TreeMode": "tree",
  "TreeNode": "tree",
  "TreeNodeItemProps": "tree",
  "TreeNodesProps": "tree",
  "TreeRootProps": "tree",
  "TreeSearchProps": "tree",
  "TreeSize": "tree",
  "TreeVariant": "tree",
  "useVideoPlayer": "video-player",
  "useVideoPlayerState": "video-player",
  "useVideoPlayerActions": "video-player",
  "VideoTrack": "video-player",
  "VideoQuality": "video-player",
  "QualityLevel": "video-player",
  "VideoPlayerState": "video-player",
  "VideoPlayerActions": "video-player",
  "VideoPlayerContextValue": "video-player",
  "VideoPlayer": "video-player"
};
