import type { DesignTokenCategory } from 'vayu-ui-registry';

export const designTokenCategories: DesignTokenCategory[] = [
  {
    name: 'Base Layers',
    tokens: [
      {
        name: 'canvas',
        tailwindClass: 'bg-canvas',
        lightValue: '#ffffff',
        darkValue: '#09090b',
        description: 'App-level background — outermost container',
        group: 'color',
        relatedClasses: ['text-canvas-content'],
      },
      {
        name: 'canvas-content',
        tailwindClass: 'text-canvas-content',
        lightValue: '#09090b',
        darkValue: '#fafafa',
        description: 'Primary text on canvas backgrounds',
        group: 'color',
        relatedClasses: ['bg-canvas'],
      },
      {
        name: 'surface',
        tailwindClass: 'bg-surface',
        lightValue: '#ffffff',
        darkValue: '#18181b',
        description: 'Container/card backgrounds — one level above canvas',
        group: 'color',
        relatedClasses: ['text-surface-content'],
      },
      {
        name: 'surface-content',
        tailwindClass: 'text-surface-content',
        lightValue: '#09090b',
        darkValue: '#fafafa',
        description: 'Primary text on surface backgrounds',
        group: 'color',
        relatedClasses: ['bg-surface'],
      },
      {
        name: 'elevated',
        tailwindClass: 'bg-elevated',
        lightValue: '#ffffff',
        darkValue: '#27272a',
        description: 'Modals, popovers, dropdowns — highest elevation',
        group: 'color',
        relatedClasses: ['text-elevated-content'],
      },
      {
        name: 'elevated-content',
        tailwindClass: 'text-elevated-content',
        lightValue: '#09090b',
        darkValue: '#fafafa',
        description: 'Primary text on elevated backgrounds',
        group: 'color',
        relatedClasses: ['bg-elevated'],
      },
    ],
  },
  {
    name: 'Semantic Colors',
    tokens: [
      {
        name: 'brand',
        tailwindClass: 'bg-brand',
        lightValue: '#2563eb',
        darkValue: '#3b82f6',
        description: 'Primary actions, CTAs, brand identity',
        group: 'color',
        relatedClasses: ['text-brand-content', 'border-brand'],
      },
      {
        name: 'brand-content',
        tailwindClass: 'text-brand-content',
        lightValue: '#ffffff',
        darkValue: '#ffffff',
        description: 'Text on brand backgrounds',
        group: 'color',
        relatedClasses: ['bg-brand'],
      },
      {
        name: 'success',
        tailwindClass: 'bg-success',
        lightValue: '#16a34a',
        darkValue: '#22c55e',
        description: 'Success states, confirmations',
        group: 'color',
        relatedClasses: ['text-success-content'],
      },
      {
        name: 'success-content',
        tailwindClass: 'text-success-content',
        lightValue: '#ffffff',
        darkValue: '#052e16',
        description: 'Text on success backgrounds',
        group: 'color',
        relatedClasses: ['bg-success'],
      },
      {
        name: 'warning',
        tailwindClass: 'bg-warning',
        lightValue: '#ca8a04',
        darkValue: '#eab308',
        description: 'Warning states, caution indicators',
        group: 'color',
        relatedClasses: ['text-warning-content'],
      },
      {
        name: 'warning-content',
        tailwindClass: 'text-warning-content',
        lightValue: '#ffffff',
        darkValue: '#422006',
        description: 'Text on warning backgrounds',
        group: 'color',
        relatedClasses: ['bg-warning'],
      },
      {
        name: 'destructive',
        tailwindClass: 'bg-destructive',
        lightValue: '#dc2626',
        darkValue: '#ef4444',
        description: 'Error states, destructive actions',
        group: 'color',
        relatedClasses: ['text-destructive-content'],
      },
      {
        name: 'destructive-content',
        tailwindClass: 'text-destructive-content',
        lightValue: '#ffffff',
        darkValue: '#ffffff',
        description: 'Text on destructive backgrounds',
        group: 'color',
        relatedClasses: ['bg-destructive'],
      },
      {
        name: 'info',
        tailwindClass: 'bg-info',
        lightValue: '#2563eb',
        darkValue: '#3b82f6',
        description: 'Informational states, tips',
        group: 'color',
        relatedClasses: ['text-info-content'],
      },
      {
        name: 'info-content',
        tailwindClass: 'text-info-content',
        lightValue: '#ffffff',
        darkValue: '#eff6ff',
        description: 'Text on info backgrounds',
        group: 'color',
        relatedClasses: ['bg-info'],
      },
      {
        name: 'muted',
        tailwindClass: 'bg-muted',
        lightValue: '#f4f4f5',
        darkValue: '#27272a',
        description: 'De-emphasized UI elements, subtle backgrounds',
        group: 'color',
        relatedClasses: ['text-muted-content'],
      },
      {
        name: 'muted-content',
        tailwindClass: 'text-muted-content',
        lightValue: '#71717a',
        darkValue: '#a1a1aa',
        description: 'Secondary/de-emphasized text',
        group: 'color',
        relatedClasses: ['bg-muted'],
      },
    ],
  },
  {
    name: 'Structural',
    tokens: [
      {
        name: 'border',
        tailwindClass: 'border-border',
        lightValue: '#e4e4e7',
        darkValue: '#3f3f46',
        description: 'Default border color',
        group: 'color',
      },
      {
        name: 'field',
        tailwindClass: 'bg-field',
        lightValue: '#ffffff',
        darkValue: '#18181b',
        description: 'Input field backgrounds',
        group: 'color',
      },
      {
        name: 'focus',
        tailwindClass: 'ring-focus',
        lightValue: '#2563eb',
        darkValue: '#3b82f6',
        description: 'Focus ring color for keyboard navigation',
        group: 'color',
      },
    ],
  },
  {
    name: 'Radius',
    tokens: [
      {
        name: 'rounded-control',
        tailwindClass: 'rounded-control',
        lightValue: '6px',
        darkValue: '6px',
        description: 'Inputs, buttons, small interactive elements',
        group: 'radius',
      },
      {
        name: 'rounded-surface',
        tailwindClass: 'rounded-surface',
        lightValue: '8px',
        darkValue: '8px',
        description: 'Cards, containers, list items',
        group: 'radius',
      },
      {
        name: 'rounded-overlay',
        tailwindClass: 'rounded-overlay',
        lightValue: '12px',
        darkValue: '12px',
        description: 'Modals, popovers, dropdowns',
        group: 'radius',
      },
    ],
  },
  {
    name: 'Shadows',
    tokens: [
      {
        name: 'shadow-control',
        tailwindClass: 'shadow-control',
        lightValue: '0 1px 2px rgba(0,0,0,0.05)',
        darkValue: '0 1px 2px rgba(0,0,0,0.3)',
        description: 'Buttons, inputs — subtle depth',
        group: 'shadow',
      },
      {
        name: 'shadow-surface',
        tailwindClass: 'shadow-surface',
        lightValue: '0 1px 3px rgba(0,0,0,0.1)',
        darkValue: '0 1px 3px rgba(0,0,0,0.4)',
        description: 'Cards, list items — medium depth',
        group: 'shadow',
      },
      {
        name: 'shadow-elevated',
        tailwindClass: 'shadow-elevated',
        lightValue: '0 4px 6px rgba(0,0,0,0.1)',
        darkValue: '0 4px 6px rgba(0,0,0,0.5)',
        description: 'Modals, dropdowns — highest depth',
        group: 'shadow',
      },
    ],
  },
];
